In [1]:
import pandas as pd
import geopandas as gpd
import folium
import matplotlib.pyplot as plt

geo_data = gpd.GeoDataFrame(gpd.read_file("WijkBuurtkaart_2022_v1/wijkenbuurten_2022_v1.gpkg"))

geo_data.head()

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,indelingswijziging_wijken_en_buurten,water,meest_voorkomende_postcode,dekkingspercentage,omgevingsadressendichtheid,...,percentage_uit_nederlandse_antillen_en_aruba,percentage_uit_suriname,percentage_uit_turkije,percentage_overige_nietwestersemigratieachtergrond,oppervlakte_totaal_in_ha,oppervlakte_land_in_ha,oppervlakte_water_in_ha,jrstatcode,jaar,geometry
0,BU03779998,,WK037799,GM0377,Bloemendaal,-99999999,JA,,-99999999,-99999999,...,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,2022BU03779998,2022,"MULTIPOLYGON (((98757.530 494793.560, 98752.83..."
1,BU08529997,,WK085299,GM0852,Waterland,-99999999,JA,,-99999999,-99999999,...,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,2022BU08529997,2022,"MULTIPOLYGON (((136499.997 501000.739, 136866...."
2,BU07189998,,WK071899,GM0718,Vlissingen,-99999999,JA,,-99999999,-99999999,...,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,2022BU07189998,2022,"MULTIPOLYGON (((23205.420 400019.760, 23084.51..."
3,BU03639997,,WK036399,GM0363,Amsterdam,-99999999,JA,,-99999999,-99999999,...,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,2022BU03639997,2022,"MULTIPOLYGON (((126326.284 488278.723, 126330...."
4,BU06879997,,WK068799,GM0687,Middelburg,-99999999,JA,,-99999999,-99999999,...,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,-99999999,2022BU06879997,2022,"MULTIPOLYGON (((37669.841 395253.871, 37663.47..."

In [2]:
geo_data.shape

(14412, 42)

In [3]:
geo_data = geo_data[geo_data['gemeentenaam'] == 'Groningen']
geo_data.set_crs(epsg='28992')
geo_data = geo_data.to_crs(epsg='4326')
geo_data.head()

,buurtcode,buurtnaam,wijkcode,gemeentecode,gemeentenaam,indelingswijziging_wijken_en_buurten,water,meest_voorkomende_postcode,dekkingspercentage,omgevingsadressendichtheid,...,percentage_uit_nederlandse_antillen_en_aruba,percentage_uit_suriname,percentage_uit_turkije,percentage_overige_nietwestersemigratieachtergrond,oppervlakte_totaal_in_ha,oppervlakte_land_in_ha,oppervlakte_water_in_ha,jrstatcode,jaar,geometry
95,BU00140000,Binnenstad-Noord,WK001400,GM0014,Groningen,1,NEE,9712,1,6712,...,1,1,1,8,39,37,2,2022BU00140000,2022,"MULTIPOLYGON (((6.56757 53.22222, 6.56840 53.2..."
348,BU00141406,De Wierden,WK001414,GM0014,Groningen,1,NEE,9613,1,170,...,-99999999,-99999999,-99999999,-99999999,59,52,7,2022BU00141406,2022,"MULTIPOLYGON (((6.66667 53.22460, 6.66646 53.2..."
500,BU00140103,Rivierenbuurt,WK001401,GM0014,Groningen,1,NEE,9725,1,4220,...,1,1,0,7,56,55,1,2022BU00140103,2022,"MULTIPOLYGON (((6.57132 53.21074, 6.57136 53.2..."
608,BU00141003,Zernike Campus,WK001410,GM0014,Groningen,1,NEE,9747,1,972,...,-99999999,-99999999,-99999999,-99999999,202,187,15,2022BU00141003,2022,"MULTIPOLYGON (((6.53144 53.25024, 6.53131 53.2..."
775,BU00141701,Haren-Zuidwest,WK001417,GM0014,Groningen,1,NEE,9752,1,951,...,1,0,0,4,141,140,1,2022BU00141701,2022,"MULTIPOLYGON (((6.59953 53.17689, 6.59969 53.1..."

In [4]:
print(geo_data.shape)

(150, 42)

In [5]:
print(geo_data.columns)

Index(['buurtcode', 'buurtnaam', 'wijkcode', 'gemeentecode', 'gemeentenaam',
       'indelingswijziging_wijken_en_buurten', 'water',
       'meest_voorkomende_postcode', 'dekkingspercentage',
       'omgevingsadressendichtheid', 'stedelijkheid_adressen_per_km2',
       'bevolkingsdichtheid_inwoners_per_km2', 'aantal_inwoners', 'mannen',
       'vrouwen', 'percentage_personen_0_tot_15_jaar',
       'percentage_personen_15_tot_25_jaar',
       'percentage_personen_25_tot_45_jaar',
       'percentage_personen_45_tot_65_jaar',
       'percentage_personen_65_jaar_en_ouder', 'percentage_ongehuwd',
       'percentage_gehuwd', 'percentage_gescheid', 'percentage_verweduwd',
       'aantal_huishoudens', 'percentage_eenpersoonshuishoudens',
       'percentage_huishoudens_zonder_kinderen',
       'percentage_huishoudens_met_kinderen', 'gemiddelde_huishoudsgrootte',
       'percentage_westerse_migratieachtergrond',
       'percentage_niet_westerse_migratieachtergrond',
       'percentage_uit_marokko',
       'percentage_uit_nederlandse_antillen_en_aruba',
       'percentage_uit_suriname', 'percentage_uit_turkije',
       'percentage_overige_nietwestersemigratieachtergrond',
       'oppervlakte_totaal_in_ha', 'oppervlakte_land_in_ha',
       'oppervlakte_water_in_ha', 'jrstatcode', 'jaar', 'geometry'],
      dtype='object')

In [6]:
dogs_data=pd.read_csv('honden_data.csv', sep = ";")
dogs_data['buurtcode'] = dogs_data.apply(lambda row: "BU00" + str(row['buurtnr']), axis=1)
#dogs_data['2016'] = dogs_data['2016'] if dogs_data['2016']!='.' else 0
dogs_data.head()

   buurtnr 2016  2018   buurtcode
0   140000   45    37  BU00140000
1   140001   62    51  BU00140001
2   140002   47    48  BU00140002
3   140003   16    21  BU00140003
4   140005  101   108  BU00140005

In [7]:
print(dogs_data.shape)
print(dogs_data.dtypes)

(96, 4)
buurtnr       int64
2016         object
2018          int64
buurtcode    object
dtype: object

In [8]:
dogs_data['2016'].value_counts()

.      4
5      4
2      4
10     4
8      3
      ..
136    1
153    1
124    1
144    1
52     1
Name: 2016, Length: 71, dtype: int64

In [9]:
dogs_data['2016'] = dogs_data['2016'].replace('.',0)
convert_dict = {'2016': int}
dogs_data = dogs_data.astype(convert_dict)
print(dogs_data.dtypes)

buurtnr       int64
2016          int64
2018          int64
buurtcode    object
dtype: object

In [11]:
m = folium.Map(location=[53.22222, 6.56757], zoom_start=12, tiles='CartoDB positron')

year = '2018'
from branca.colormap import linear
colormap = linear.YlOrRd_09.scale(min(dogs_data[year]),
                                            max(dogs_data[year]))
colormap.caption = 'Amount of dogs owners in Groningen in ' + year
colormap.add_to(m)


def style_fn(feature):
    #colormap = branca.colormap.LinearColormap(["white", "green"], vmin=0, vmax=100)
    most_common = feature["properties"]["dogs_amount"]
    ss = {
        "fillColor": colormap(most_common),
        "fillOpacity": 0.9,
        "weight": 0.9,
        "opacity": 1,
        "color": "black",
    }
    return ss

def get_dogs_amount(row):
    dogs_row = dogs_data[dogs_data['buurtcode'] == row['buurtcode']]
    dogs = 0 if dogs_row.empty else dogs_row[year].iloc[0]
    return dogs

def get_age_area(row):
    max_percent = max([row['percentage_personen_0_tot_15_jaar'],
                  row['percentage_personen_15_tot_25_jaar'],
                  row['percentage_personen_25_tot_45_jaar'],
                  row['percentage_personen_45_tot_65_jaar'],
                  row['percentage_personen_65_jaar_en_ouder']])
    result = "0 tot 15 jaar" if max_percent == row['percentage_personen_0_tot_15_jaar'] else " "
    result = "15 tot 25 jaar" if max_percent == row['percentage_personen_15_tot_25_jaar'] else " "
    result = "25 tot 45 jaar" if max_percent == row['percentage_personen_45_tot_65_jaar'] else " "
    result = "45 tot 65 jaar" if max_percent == row['percentage_personen_0_tot_15_jaar'] else " "
    result = "65 jaar en ouder" if max_percent == row['percentage_personen_65_jaar_en_ouder'] else " "
    return result
                                                    

def get_marital_status(row):
    max_percent = max([row['percentage_ongehuwd'],
                  row['percentage_gehuwd'],
                  row['percentage_gescheid'],
                  row['percentage_verweduwd']])
    result = "ongehuwd" if max_percent == row['percentage_ongehuwd'] else ""
    result = "gehuwd" if max_percent == row['percentage_gehuwd'] else ""
    result = "gescheid" if max_percent == row['percentage_gescheid'] else ""
    result = "verweduwd" if max_percent == row['percentage_verweduwd'] else ""

def get_buurt_naam(row):
    return row["buurtnaam"]
    
geo_data['dogs_amount'] = geo_data.apply(lambda row: get_dogs_amount(row), axis=1)
geo_data['often_age'] = geo_data.apply(lambda row: get_age_area(row), axis=1)
geo_data['marital_status'] = geo_data.apply(lambda row: get_marital_status(row), axis=1)
geo_data['name'] = geo_data.apply(lambda row: get_buurt_naam(row), axis=1)

folium.GeoJson(
    geo_data.__geo_interface__,
    style_function=style_fn,
    popup=folium.GeoJsonPopup(fields=['dogs_amount']),
    tooltip=folium.features.GeoJsonTooltip(['name', "dogs_amount", "often_age", 'marital_status']),
).add_to(m)

m

SyntaxError: expected 'else' after 'if' expression (580990086.py, line 34)